"""add_share_token

Revision ID: 65772979faa1
Revises: 9bfaf9631dec
Create Date: 2026-10-07 21:24:31.250431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '65772979faa1'
down_revision: Union[str, Sequence[str], None] = '9bfaf9631dec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cv_share_tokens',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('vault_id', sa.String(length=39), nullable=False),
    sa.Column('verifier_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('expires_at', sa.String(length=40), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['cv_users.id'], ),
    sa.ForeignKeyConstraint(['verifier_id'], ['cv_organizations.id'], ),
    sa.PrimaryKeyConstraint('token_hash')
    )
    op.create_index(op.f('ix_cv_share_tokens_owner_id'), 'cv_share_tokens', ['owner_id'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_verification_requests_id'), table_name='verification_requests')
    op.drop_table('verification_requests')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_document_fields_id'), table_name='document_fields')
    op.drop_table('document_fields')
    op.drop_index(op.f('ix_consent_rules_id'), table_name='consent_rules')
    op.drop_table('consent_rules')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_issuers_id'), table_name='issuers')
    op.drop_table('issuers')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issuers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('issuer_type', postgresql.ENUM('GOVERNMENT', 'EDUCATIONAL', name='issuertype'), autoincrement=False, nullable=False),
    sa.Column('public_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('verified', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('issuers_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('issuers_pkey'))
    )
    op.create_index(op.f('ix_issuers_id'), 'issuers', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('actor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('actor_role', postgresql.ENUM('OWNER', 'ISSUER', 'VERIFIER', name='userrole'), autoincrement=False, nullable=False),
    sa.Column('action', postgresql.ENUM('REQUEST_CREATED', 'AUTO_APPROVED', 'USER_APPROVED', 'USER_DENIED', 'REQUEST_DENIED', 'SELECTIVE_DISCLOSURE', 'DOCUMENT_ISSUED', 'DOCUMENT_REVOKED', 'CONSENT_RULE_CREATED', name='auditaction'), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fields_requested', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('fields_shared', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('decision', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('approval_method', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('audit_logs_actor_id_fkey')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('audit_logs_document_id_fkey')),
    sa.ForeignKeyConstraint(['request_id'], ['verification_requests.id'], name=op.f('audit_logs_request_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_logs_pkey'))
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('consent_rules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('verifier_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('field_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('action', postgresql.ENUM('AUTO_APPROVE', 'ASK', 'DENY', name='consentaction'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('consent_rules_document_id_fkey')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('consent_rules_owner_id_fkey')),
    sa.ForeignKeyConstraint(['verifier_id'], ['users.id'], name=op.f('consent_rules_verifier_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('consent_rules_pkey'))
    )
    op.create_index(op.f('ix_consent_rules_id'), 'consent_rules', ['id'], unique=False)
    op.create_table('document_fields',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('field_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('field_value_encrypted', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('field_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_sensitive', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('document_fields_document_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('document_fields_pkey'))
    )
    op.create_index(op.f('ix_document_fields_id'), 'document_fields', ['id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('issuer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('category', postgresql.ENUM('GOVERNMENT', 'EDUCATION', name='documentcategory'), autoincrement=False, nullable=False),
    sa.Column('document_type', postgresql.ENUM('AADHAAR_STYLE', 'PAN_STYLE', 'PASSPORT', 'DRIVING_LICENSE', 'DEGREE_CERTIFICATE', 'MARKSHEET', name='documenttype'), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('document_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('signature', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('issued_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('expiry_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('VERIFIED', 'PENDING', 'REVOKED', name='documentstatus'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['issuer_id'], ['issuers.id'], name=op.f('documents_issuer_id_fkey')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('documents_owner_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('documents_pkey'))
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('verification_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('verifier_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('requested_fields', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'APPROVED', 'DENIED', name='verificationstatus'), autoincrement=False, nullable=False),
    sa.Column('decision_reason', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('verification_requests_document_id_fkey')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('verification_requests_owner_id_fkey')),
    sa.ForeignKeyConstraint(['verifier_id'], ['users.id'], name=op.f('verification_requests_verifier_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('verification_requests_pkey'))
    )
    op.create_index(op.f('ix_verification_requests_id'), 'verification_requests', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('OWNER', 'ISSUER', 'VERIFIER', name='userrole'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_cv_share_tokens_owner_id'), table_name='cv_share_tokens')
    op.drop_table('cv_share_tokens')
    # ### end Alembic commands ###
