"""Add vault_id

Revision ID: 9bfaf9631dec
Revises: cv5_live_updates
Create Date: 2026-10-07 20:39:26.344943

"""
from typing import Sequence, Union

from alembic import op
import uuid
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9bfaf9631dec'
down_revision: Union[str, Sequence[str], None] = 'cv5_live_updates'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cv_users', sa.Column('vault_id', sa.String(length=64), nullable=True))

    connection = op.get_bind()
    users = connection.execute(sa.text(
        "SELECT u.id FROM cv_users u JOIN cv_memberships m ON u.id = m.user_id WHERE m.role = 'OWNER'"
    )).fetchall()
    for (user_id,) in users:
        new_vault_id = 'CV-' + str(uuid.uuid4()).upper()
        connection.execute(sa.text(
            "UPDATE cv_users SET vault_id = :vault_id WHERE id = :user_id"
        ), {"vault_id": new_vault_id, "user_id": user_id})

    op.create_index(op.f('ix_cv_users_vault_id'), 'cv_users', ['vault_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cv_users_vault_id'), table_name='cv_users')
    op.drop_column('cv_users', 'vault_id')
    # ### end Alembic commands ###
